Always run the lock/unlock scripts completely
ben-z/gh-action-mutex pull request #7
Opened 2022-05-03 18:07 UTC by chamini2

This will avoid leaving the lock in an unexpected state

#6

2022-05-03 18:09 UTC, chamini2 commented
From the [docs](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run)

2022-05-03 18:13 UTC, chamini2 commented on action.yml
> +  if: ${{ always() }}
I only see documented `post-if` https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#post-entrypoint

Maybe we have to remove this line

2022-05-03 18:15 UTC, chamini2 commented on action.yml
> +  if: ${{ always() }}
And it seems it handles it well enough: https://github.com/ben-z/gh-action-mutex/blob/bc97a5192de56202e1b5d1d3eeca2ecbbef8523c/rootfs/scripts/utils.sh#L101-L105

2022-05-05 02:32 UTC, ben-z requested changes
I think the change is already the default behaviour. The test is good, though we might want to check to see how we can have the pipeline pass while still test for this behaviour.

2022-05-05 02:32 UTC, ben-z commented on action.yml
> +  post-if: ${{ always() }}
I'm pretty sure this is already the default. The current behaviour is already "if a step fails, the lock gets cleaned up".

2022-05-05 02:32 UTC, ben-z commented on action.yml
> +  post-if: ${{ always() }}
Here's the doc: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost-if

2022-05-05 02:32 UTC, ben-z commented on .github/workflows/main.yml
> +  always_unlock_test_1:
These are good tests!

Would this job show up as failed? I'm not sure how to best test this while still having the job pass. Perhaps we can run the check in a subsequent step?

2022-05-05 02:33 UTC, ben-z commented
The workflow didn't run, am I configuring the workflow properly? Perhaps it should be `pull_request_target` instead of `pull_request`? https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

2022-05-05 02:34 UTC, ben-z commented
Oh I see I don't run the PR on pull requests at all 😆 https://github.com/ben-z/gh-action-mutex/blob/271919c55332938179960557fcf28c8fa78be691/.github/workflows/main.yml#L1

2022-05-05 16:33 UTC, ben-z commented on action.yml
> +  post-if: ${{ always() }}
I think the difference is in “canceling” vs “failing”. When we cancel a job I’m pretty sure the whole pipeline just gets terminated. When a step fails the pipeline keeps running, which is when the post jobs are triggered

2022-05-22 16:46 UTC, ben-z commented
> Here you have an example of this failing: https://github.com/fal-ai/fal/runs/6264956528?check_suite_focus=true
> 
> Since we had many in the same workflow waiting for the lock, they came to unlock in an unexpected order and some of them just raised "we don't have the lock" errors but then when they did have it, they already had stopped.

I can't seem to find the "we don't have the lock" error. Can you point me to it?

2022-05-23 12:21 UTC, chamini2 commented
![image](https://user-images.githubusercontent.com/2745502/169818152-90c143a5-1e03-41ed-845f-8d20abc1458c.png)

2022-05-25 22:51 UTC, chamini2 commented
Here you can see the use case in action: 3 waiting jobs are cancelled at the same time and we handle it fine: https://github.com/fal-ai/fal/runs/6601366282?check_suite_focus=true

2022-05-31 03:27 UTC, ben-z commented
Oh I see! You are right, the post job assumes that we have the lock. If the post job runs before we even obtain the lock, it's going to fail.

Good changes. I will look again

2022-05-31 03:29 UTC, ben-z commented on rootfs/scripts/utils.sh
> +unqueue() {
Can we rename this to `dequeue`? I think that's the more common word for this action

2022-05-31 03:29 UTC, ben-z commented on rootfs/scripts/utils.sh
> +	if [ "$(cat $__queue_file | awk NF | head -n 1)" != "$__ticket_id" ]; then
I'd reverse the logic here, change `!=` to `==` and swap the if and else blocks

2022-06-03 14:48 UTC, chamini2 commented
Changes done @ben-z!

2022-06-04 20:50 UTC, ben-z approved these changes
LGTM! Thanks for the patch!

2022-06-04 20:50 UTC, merged

2022-06-04 22:15 UTC, ben-z commented
I had to remove the test because I don't see a clear way for them to have a passing status and still test what we want to test: https://github.com/ben-z/gh-action-mutex/commit/54229dd30dfc55e4dbb705e0c7dfd27e511fc6e6

2022-06-05 21:20 UTC, chamini2 commented
Understood, @ben-z. Thanks for merging. Will you do an alpha release with this?

2022-06-06 04:48 UTC, ben-z commented
True, good idea! https://github.com/ben-z/gh-action-mutex/releases/tag/v1.0-alpha-5